### ISSUE TITLE
BUILD FAILURE due to test

### ISSUE THREAD

**Issue by SavvyShark** [downgoon/gbk2utf8#3]
`mvn clean package` failed. I have to skip test to build jar file.

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building gbk2utf8 0.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gbk2utf8 ---
[INFO] Deleting D:\Projects\github\gbk2utf8\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gbk2utf8 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Projects\github\gbk2utf8\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ gbk2utf8 ---
[INFO] Compiling 3 source files to D:\Projects\github\gbk2utf8\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gbk2utf8 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Projects\github\gbk2utf8\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ gbk2utf8 ---
[INFO] Compiling 2 source files to D:\Projects\github\gbk2utf8\target\test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ gbk2utf8 ---
[INFO] Surefire report directory: D:\Projects\github\gbk2utf8\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.downgoon.tools.Gbk2Utf8Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec
Running io.downgoon.tools.PackageRenameTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
testReplacement(io.downgoon.tools.PackageRenameTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<src/main/java/[io/downgoon]/tools/Hello.java> but was:<src/main/java/[com/example]/tools/Hello.java>
	at org.junit.Assert.assertEquals(Assert.java:99)
	at org.junit.Assert.assertEquals(Assert.java:117)
	at io.downgoon.tools.PackageRenameTest.testReplacement(PackageRenameTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   testReplacement(io.downgoon.tools.PackageRenameTest): expected:<src/main/java/[io/downgoon]/tools/Hello.java> but was:<src/main/java/[com/example]/tools/Hello.java>

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.042 s
[INFO] Finished at: 2017-04-28T15:51:19+08:00
[INFO] Final Memory: 24M/314M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project gbk2utf8: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\Projects\github\gbk2utf8\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

``` 
skip test
```
D:\Projects\github\gbk2utf8 (master)
$ mvn clean package -DskipTests
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building gbk2utf8 0.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gbk2utf8 ---
[INFO] Deleting D:\Projects\github\gbk2utf8\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gbk2utf8 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Projects\github\gbk2utf8\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ gbk2utf8 ---
[INFO] Compiling 3 source files to D:\Projects\github\gbk2utf8\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gbk2utf8 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Projects\github\gbk2utf8\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ gbk2utf8 ---
[INFO] Compiling 2 source files to D:\Projects\github\gbk2utf8\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ gbk2utf8 ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ gbk2utf8 ---
[INFO] Building jar: D:\Projects\github\gbk2utf8\target\gbk2utf8-0.1.1-SNAPSHOT.jar
[INFO]
[INFO] --- maven-shade-plugin:2.0:shade (default) @ gbk2utf8 ---
[INFO] Including commons-io:commons-io:jar:2.5 in the shaded jar.
[INFO] Minimizing jar io.downgoon.tools:gbk2utf8:jar:0.1.1-SNAPSHOT
[INFO] Minimized 136 -> 44 (32%)
[INFO] Attaching shaded artifact.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.960 s
[INFO] Finished at: 2017-04-28T15:53:30+08:00
[INFO] Final Memory: 23M/308M
[INFO] ------------------------------------------------------------------------
```

**Comment by downgoon** [comment]
@febzhang thanks for your feedback. the problem lays in the differences between linux
and windows on FileSystem Path delimiter （in linux is '/', while in windows is '\\'）.  so, the test case passed in my Mac, while failed on your windows.
